### ISSUE TITLE
Configuring  openocd-master error with libftdi 

### ISSUE THREAD

**Issue by ovnicraft** [esden/summon-arm-toolchain#2] opened 2011-01-30 15:45 UTC
The README file can be explict in this requirement with opencd-master

**Comment by esden** [comment] 2011-02-17 18:54
I don't exactly understand what you mean by this issue. Can you elaborate please?

**Comment by ovnicraft** [comment] 2011-02-17 18:56
The installation require openocd-master what is never named in README file so i think must be included.

regards,

**Comment by esden** [comment] 2011-02-17 19:14
But the script is downloading this openocd-master by itself. We are listing only packages that have to be installed by the user using the packge manager of the operating system in use. But I may misunderstand something still. :) The only issue that I know about is that if you once downloaded openocd-master it is not refetching it if there were additional commits upstream. Maybe we should change the script to checkout a specific SHA of openocd so that everyone has a defined state and not just some arbitrary upstream master depending on the time the user is running the script?

**Comment by up4** [comment] 2011-05-29 18:31
Hi Guys,

I sent a message to Piotr about this already. Happens to me on my 2009 iMac Core i5 running Mac OS X 10.6.7 when trying TARGET=arm-elf

It crashes at "Configuring openocd-master" with 

"checking Build & Link with libftdi...... configure: error: Cannot build & run test program using libftdi"

I don't know where to go from there…

**Comment by esden** [comment] 2011-05-29 22:40
Hi,

So I just compiled SAT from scratch again. It is finding libftdi with the newest openocd.

I found though that libopenstm32 has issues compiling with arm-eabi version of sat. I am not sure yet what the issue is there.

**Comment by ovnicraft** [comment] 2011-06-10 16:49
@Esde well check the script to get opencd-master :)

Regards,

**Comment by esden** [comment] 2013-01-22 03:08
I guess this is fixed now? :) Closing...

**Closed as completed by esden** 2013-01-22 03:08 UTC
